### ISSUE TITLE
Difference to WHATWG fetch

### ISSUE THREAD

**Issue by surma** [WinterTC55/fetch#16]
As `fetch()` is a fairly well-known API, and a bunch of folks are used to consulting the WHATWG fetch, would it make sense to have a section in the WinterCG spec that summarizes where the differences between these two specs are? 

I think that would help a couple of decision makers feel more comfortable following the WinterCG spec where appropriate.

(This is probably generally true for WinterCG specs that are forks of existing web specs.)

**Comment by ljharb** [comment]
Yes, it would, as i think there are a lot of subtle footguns in using something that has the same name and works *almost* the same.

**Comment by igrigorik** [comment]
I would **love** to see an explicit section at the top of the doc that speaks to the diffs.

**Comment by andreubotella** [comment]
Currently there are no differences yet, except for the styling/boilerplate and the abstract. (And except for upstream updates that we haven't pulled yet.) We haven't yet gotten started with any actual changes. But I'm working on an "about this fork" introduction that will include a list of changes to be updated as they're worked on.

**Comment by ljharb** [comment]
@andreubotella i'm not sure how that could be true - non-browsers don't have a concept of the current URL and thus of cookies on it, etc. or do you just mean this *repo* has no differences yet?

**Comment by andreubotella** [comment]
> @andreubotella i'm not sure how that could be true - non-browsers don't have a concept of the current URL and thus of cookies on it, etc. or do you just mean this _repo_ has no differences yet?

That is what I meant, indeed.

**Comment by bergus** [comment]
Could you also add a section to detail how this specification is to be understood? Is it normative (for whom)? Is it meant as a source for pull requests into WHATWG fetch? How does this fit with https://wintercg.org/faq#what-we-are-not-trying-to-do

> We will never fork or create new versions of existing specifications. For any change we propose, the goal is always for it to be incorporated into an upstream spec in an existing venue (such as WHATWG or W3C).
